spring:
  application:
    name: ms-assinaturas
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
hystrix:
  command:
    testCallTwo:
      execution:
        isolation.thread.timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 2  # For testing purposes